//match

export const SET_LIVE_MATCHS = 'SET_LIVE_MATCHS'
export const SET_MATCH_LINK = 'SET_MATCH_LINK'

export const SET_MATCH_LINK_INFO = 'SET_MATCH_LINK_INFO'
export const SET_MATCH_INDEX = 'SET_MATCH_INDEX'
export const SET_MATCH_LINK_INDEX = 'SET_MATCH_LINK_INDEX'
